// flow-typed signature: 021773e80517b5dcca7d84c2e2df2a55
// flow-typed version: <<STUB>>/styletron-react_v^2.5.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-react/lib/index' {
  declare module.exports: any;
}

declare module 'styletron-react/lib/is-valid-attr' {
  declare module.exports: any;
}

declare module 'styletron-react/lib/provider' {
  declare module.exports: any;
}

declare module 'styletron-react/lib/styled' {
  declare module.exports: any;
}

declare module 'styletron-react/lib/test/browser' {
  declare module.exports: any;
}

declare module 'styletron-react/src/index' {
  declare module.exports: any;
}

declare module 'styletron-react/src/is-valid-attr' {
  declare module.exports: any;
}

declare module 'styletron-react/src/provider' {
  declare module.exports: any;
}

declare module 'styletron-react/src/styled' {
  declare module.exports: any;
}

declare module 'styletron-react/src/test/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-react/lib/index.js' {
  declare module.exports: $Exports<'styletron-react/lib/index'>;
}
declare module 'styletron-react/lib/is-valid-attr.js' {
  declare module.exports: $Exports<'styletron-react/lib/is-valid-attr'>;
}
declare module 'styletron-react/lib/provider.js' {
  declare module.exports: $Exports<'styletron-react/lib/provider'>;
}
declare module 'styletron-react/lib/styled.js' {
  declare module.exports: $Exports<'styletron-react/lib/styled'>;
}
declare module 'styletron-react/lib/test/browser.js' {
  declare module.exports: $Exports<'styletron-react/lib/test/browser'>;
}
declare module 'styletron-react/src/index.js' {
  declare module.exports: $Exports<'styletron-react/src/index'>;
}
declare module 'styletron-react/src/is-valid-attr.js' {
  declare module.exports: $Exports<'styletron-react/src/is-valid-attr'>;
}
declare module 'styletron-react/src/provider.js' {
  declare module.exports: $Exports<'styletron-react/src/provider'>;
}
declare module 'styletron-react/src/styled.js' {
  declare module.exports: $Exports<'styletron-react/src/styled'>;
}
declare module 'styletron-react/src/test/browser.js' {
  declare module.exports: $Exports<'styletron-react/src/test/browser'>;
}
